version: '2'
services:

  cassandra4:
    image: datastax/cassandra-mgmtapi-4_0_0:v0.1.2
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    environment:
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_CLUSTER_NAME: spring_demo_cluster
      CASSANDRA_NUM_TOKENS: 1  
      CASSANDRA_SEED: 
    volumes:
       - ~/docker-volumes/cassandra4/:/var/lib/cassandra/data
    ulimits:
      memlock: -1
      
#  cassandra3:
#    image: cassandra:3.11.6
#    ports:
#      - 7000:7000
#      - 7001:7001
#      - 7199:7199
#      - 9042:9042
#      - 9160:9160
#    environment:
#      CASSANDRA_DC: dc1
#      CASSANDRA_RACK: rack1
#      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
#      CASSANDRA_CLUSTER_NAME: spring_demo_cluster
#      CASSANDRA_NUM_TOKENS: 1  
#    volumes:
#      - ~/docker-volumes/cassandra3/:/var/lib/cassandra/data
#    ulimits:
#      memlock: -1
      
      
#    networks:
#      - dc1ring  

#networks:
#  dc1ring:
#    driver: bridge          

# If you want to have cqlsh
#  docker exec -it `docker ps | grep cassandra-mgmtapi-4_0_0:v0.1.2 | cut -b 1-12` cqlsh
   
  