server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: http://localhost:8083/
          predicates:
            - Path=/api/search/product/**
            - Path=/api/add/product/**
            - Path=/api/delete/product/**
        - id: orders
          uri: http://localhost:8081/
          prediates:
            - Path=
