version: '2'
services:
  cassandra4-node1: 
    image: datastax/cassandra-mgmtapi-4_0_0:v0.1.2
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - 9042:9042
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f -R'
    environment:
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_CLUSTER_NAME: spring_demo_cluster
      CASSANDRA_NUM_TOKENS: 1  
      CASSANDRA_SEEDS: cassandra4-node1
    volumes:
      - ~/docker-volumes/cassandra4-dc1-node1/:/var/lib/cassandra/data
    networks:
      - dc1ring
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
      
  cassandra4-node2:
    image: datastax/cassandra-mgmtapi-4_0_0:v0.1.2
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    # In case this is the first time starting up cassandra we need to ensure
    # that all nodes do not start up at the same time. Cassandra has a
    # 2 minute rule i.e. 2 minutes between each node boot up. Booting up
    # nodes simultaneously is a mistake. This only needs to happen the firt
    # time we bootup. Configuration below assumes if the Cassandra data
    # directory is empty it means that we are starting up for the first
    # time.
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 60; fi && /docker-entrypoint.sh cassandra -f -R'
    depends_on: 
      - cassandra4-node1
    environment:
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_CLUSTER_NAME: spring_demo_cluster
      CASSANDRA_NUM_TOKENS: 1  
      CASSANDRA_SEEDS: cassandra4-node1
    volumes:
      - ~/docker-volumes/cassandra4-dc1-node2/:/var/lib/cassandra/data
    networks:
      - dc1ring
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000 
      
  cassandra4-node3: 
    image: datastax/cassandra-mgmtapi-4_0_0:v0.1.2
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    # In case this is the first time starting up cassandra we need to ensure
    # that all nodes do not start up at the same time. Cassandra has a
    # 2 minute rule i.e. 2 minutes between each node boot up. Booting up
    # nodes simultaneously is a mistake. This only needs to happen the firt
    # time we bootup. Configuration below assumes if the Cassandra data
    # directory is empty it means that we are starting up for the first
    # time.
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 120; fi && /docker-entrypoint.sh cassandra -f -R'
    depends_on: 
      - cassandra4-node1
    environment:
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_CLUSTER_NAME: spring_demo_cluster
      CASSANDRA_NUM_TOKENS: 1  
      CASSANDRA_SEEDS: cassandra4-node1
    volumes:
      - ~/docker-volumes/cassandra4-dc1-node3/:/var/lib/cassandra/data
    networks:
      - dc1ring
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000          
 
# I want to access ny cluster from host      
networks:
  dc1ring:
    driver: bridge